name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: npm install

      - run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: npm install

      - run: npm run test

      - uses: codecov/codecov-action@v1

      - run: npm run build

      - name: Verify dist/index.js is updated
        run: |
          git_diff=$(git diff)
          if [ ! -z "$git_diff" ]; then
            echo $git_diff
            exit 1
          fi

  test-run:
    needs: [lint, test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./
