name: CI

on:
  issues:
    types:
      - labeled

  pull_request:
    types:
      - labeled

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
